<?php

namespace Database\Seeders\Permissions;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModelHasPermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('model_has_permissions')->insert([
            ['permission_id' => 1, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 2, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 3, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 4, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 5, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 6, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 7, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 8, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 9, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 11, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 12, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 13, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 13, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 14, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 14, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 14, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 15, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 15, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 15, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 16, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 16, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 16, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 17, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 17, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 17, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 18, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 18, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 18, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 19, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 19, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 19, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 20, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 20, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 20, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 37, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 37, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 37, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 38, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 38, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 38, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 39, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 39, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 39, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 40, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 40, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 40, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 41, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 41, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 41, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 42, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 42, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 42, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 43, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 43, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 43, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 44, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 44, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 44, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 45, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 45, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 45, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 46, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 46, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 46, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 47, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 47, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 47, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 48, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 48, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 48, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 49, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 49, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 49, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 50, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 50, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 50, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 51, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 51, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 51, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 52, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 52, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 52, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 53, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 53, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 53, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 60, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 60, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 60, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 61, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 61, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 61, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 62, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 62, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 62, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 63, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 63, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 63, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 64, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 1],
            ['permission_id' => 64, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 3],
            ['permission_id' => 64, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 65, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 69, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 70, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 71, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 72, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 73, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 74, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
            ['permission_id' => 75, 'model_type' => 'Spatie\Permission\Models\Role', 'model_id' => 4],
        ]);
    }
}
